### PR TITLE
[WIP] Add runscripts for runit and s6 from Void

### PR DESCRIPTION
**Pull request by konimex**
This PR is moved from https://github.com/artix-linux/system/pull/13

All packages have been built, but for the time being I only tested elogind, cgmanager, and dbus.

Some packages have been commented because (at least for runit) `runit-artix` provides some of them (including `cryptsetup`, `lvm` -apart from `lvmetad`-, and `kmod`).

elogind requires https://github.com/artix-linux/runit-artix/pull/1 to be merged first.

## Issues

- Is `wpa_cli.sh` really needed for wpa_supplicant?

### CODE REVIEW

**Comment by cromerc** [comment]
If possible could you guys redo this pull request? The issue is that it is impossible to merge this because of our continuous integration system. All commits of this type need the pull request to be done against the "testing" branch. I want to merge this, but can't unless it is done against our testing branch.

**Comment by thefallenrat** [comment]
No need to redo the pull request. You can do that by clicking on the edit button

**Comment by cromerc** [comment]
That wasn't the only reason I had asked. If you look at the merge section, there are conflicts and it can't be merged. This is because something changed in our repos that conflicts with the commits.

**Comment by thefallenrat** [comment]
That wasn't merge conflict. That's just buildbot failed to build the package

**Comment by udeved** [comment]
You need to merge 3rd party PRs as squash merge in order to be built in testing repos.

**Comment by cromerc** [comment]
Was not aware of that, I did a bump to that package so that it will be built:
https://github.com/artix-linux/world/commit/dc37c19d347e212a3f0f04f489487366061648a7

**Pull request merged**
