### PR TITLE
Add yaourt to world repo

### PR DESCRIPTION
**Pull request by thefallenrat**
Hey folks. Can I add yaourt to the world repo, please?

### CODE REVIEW

**Comment by cromerc** [comment]
You should add it to galaxy. Galaxy is the "community" repo for artix. World is maintained by the artix developers.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thefallenrat** [comment]
Ooops, sorry! Got it confused... Should I closed this?

**Comment by cromerc** [comment]
If you want, I would normally close it myself, but this android app does not have that option. If not I will close it later.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thefallenrat** [comment]
Alright. I will close this now and later will file a pull request on galaxy repo soon!

**Comment by cromerc** [comment]
Nevermind, found the close option...

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
